---
apiVersion: v1
kind: Service
metadata:
  name: dap-service-node
  labels:
    app: dap-service-node
spec:
  ports:
  - port: 443
    name: https
  selector:
    app: dap-service-node
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dap-service-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dap-service-node
  template:
    metadata:
      labels:
        app: dap-service-node
        name: dap-service-node
        role: master
    spec:
      serviceAccountName: dap-authn-service
      nodeSelector:
        dap-master-host: "true"
      containers:
      - name: conjur-appliance
        image: jodyhuntatx/dap:11.7.0
        imagePullPolicy: IfNotPresent
        env:
        ports:
        - containerPort: 443
          name: https
        - containerPort: 5432
          name: pg-main
        - containerPort: 1999
          name: pg-audit
        readinessProbe:
          httpGet:
            path: /health
            port: 443
            scheme: HTTPS
          initialDelaySeconds: 15
          timeoutSeconds: 5
        resources:
          requests:
            cpu: "1000m"
            memory: 4Gi
          limits:
            cpu: "1000m"
            memory: 4Gi
