---
# Create service account for MySql db
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-db
  namespace: cyberlab

---
kind: Service
apiVersion: v1
metadata:
  name: mysql-db
  namespace: cyberlab
spec:
  selector:
    app: mysql-db
  ports:
    - port: 3306
      targetPort: 3306

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-db
  labels:
    app: mysql-db
spec:
  serviceName: mysql-db
  selector:
    matchLabels:
      app: mysql-db
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      serviceAccountName: mysql-db
      containers:
      - name: mysql-db
        image: mysql:5.7.32
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3306
        env:
          - name: MYSQL_RANDOM_ROOT_PASSWORD
            value: "yes"
          - name: MYSQL_USER
            value: test_app
          - name: MYSQL_PASSWORD
            value: UhGfMk5L
          - name: MYSQL_DATABASE
            value: test_app
