---
# Define project namespace
apiVersion: v1
kind: Namespace
metadata:
  name: user4
  labels:
    name: user4

---
# Grant the authentication service access to pods in user4 namespace
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dap-authn-service
  namespace: user4
subjects:
- kind: ServiceAccount
  name: dap-authn-service
  namespace: cyberlab
roleRef:
  kind: ClusterRole
  name: dap-authn-role
  apiGroup: rbac.authorization.k8s.io

---
# Grant namespace admin privileges to user4 user & labadmin SA
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: namespace-admin
  namespace: user4
subjects:
- kind: User
  name: user4
- kind: User
  name: system:serviceaccount:user4:labadmin
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
