---
# Define project namespace
apiVersion: v1
kind: Namespace
metadata:
  name: user3
  labels:
    name: user3

---
# Grant the authentication service access to pods in user3 namespace
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dap-authn-service
  namespace: user3
subjects:
- kind: ServiceAccount
  name: dap-authn-service
  namespace: cyberlab
roleRef:
  kind: ClusterRole
  name: dap-authn-role
  apiGroup: rbac.authorization.k8s.io

---
# Grant namespace admin privileges to user3 user & labadmin SA
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: namespace-admin
  namespace: user3
subjects:
- kind: User
  name: user3
- kind: User
  name: system:serviceaccount:user3:labadmin
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
